apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: public.ecr.aws/q0f3d6q0/frontend:21
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://k8s-threetie-mainlb-11c5700e30-291009476.us-east-1.elb.amazonaws.com/api/tasks"
        ports:
        - containerPort: 3000
